sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t mattstone93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mattstone93/react-test npm test

after_success:
  - docker build -t mattstone93/multi-client ./client
  - docker build -t mattstone93/multi-server ./server
  - docker build -t mattstone93/multi-nginx ./nginx
  - docker build -t mattstone93/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mattstone93/multi-client
  - docker push mattstone93/multi-server
  - docker push mattstone93/multi-nginx
  - docker push mattstone93/multi-worker

deploy:
  provide: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-148086162012
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
