sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t mattstone93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mattstone93/react-test npm test

after_success:
  - docker build -t mattstone93/multi-client ./client
  - docker build -t mattstone93/multi-server ./server
  - docker build -t mattstone93/multi-nginx ./nginx
  - docker build -t mattstone93/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mattstone93/multi-client
  - docker push mattstone93/multi-server
  - docker push mattstone93/multi-nginx
  - docker push mattstone93/multi-worker
